# Introduction

Air Quality is assessed in Europe using the concentration of 5 pollutants - NO2, O3, PM10, PM2.5 and SO2. The data source I used was [Geod'Air](https://www.geodair.fr/).

In this notebook you can see how I collected the initial dataset for pollutants.

# Downloading raw data

I used the [Advanced Export](https://www.geodair.fr/donnees/export-advanced) functionality on the Geod'Air site for the bulk download of data. Initially I wasn't sure which pollutants would be needed, so in addition to the 5 mentioned above I download data for C6H6, CO and NOx as NO2.

First I identified the measuring stations in or close to Montpellier using the fields on the download page and the [map](https://www.geodair.fr/donnees/referentiel-mesure).

I then downloaded data for each pollutant seperately into a folder of the form `data/Air Quality/Historical to 2022-08-29/{Pollutant}`. For some pollutants, the download was split into several files as Geod'air has a limit on the download size. In these cases, the files were combined manually using Excel into a single file. In each case the final file for each pollutant is simply named `{Pollutant}.csv`. So for example, the data for sulphur dioxide is found in a file with the path `data/Air Quality/Historical to 2022-08-29/{Pollutant}/{Pollutant}.csv`.

# Processing data

First we merge the data in the separate pollutant files into single dataframe.

In [1]:
import numpy as np
import pandas as pd

In [2]:
all_pollutants = ['C6H6', 'CO', 'NO2', 'NOx as NO2', 'O3', 'PM10', 'PM25', 'SO2']

In [3]:
pollutant_data_dfs = []
for pollutant in all_pollutants:
    pollutant_data_path = f"data/Air Quality/Historical to 2022-08-29/{pollutant}/{pollutant}.csv"
    pollutant_data_df = pd.read_csv(pollutant_data_path, index_col = 0)
    pollutant_data_dfs.append(pollutant_data_df)

In [4]:
pollutants_data_df = pd.concat(pollutant_data_dfs)

In [5]:
pollutants_data_df

,Date de fin,Organisme,code zas,Zas,code site,nom site,type d'implantation,Polluant,type d'influence,Réglementaire,...,valeur,valeur brute,unité de mesure,taux de saisie,couverture temporelle,couverture de données,code qualité,validité,Latitude,Longitude
Date de début,,,,,,,,,,,,,,,,,,,,,
2013-01-02 00:00:00,2013-01-02 01:00:00,ATMO SUD,FR02N30,PROVENCE-ALPES-COTE-D-AZUR-ZI,FR02001,Berre l'Etang,Périurbaine,C6H6,Industrielle,Oui,...,0.38,0.37500,µg-m3,NaN,NaN,NaN,A,1,43.486234,5.171939
2013-01-02 01:00:00,2013-01-02 02:00:00,ATMO SUD,FR02N30,PROVENCE-ALPES-COTE-D-AZUR-ZI,FR02001,Berre l'Etang,Périurbaine,C6H6,Industrielle,Oui,...,0.00,0.00000,µg-m3,NaN,NaN,NaN,A,1,43.486234,5.171939
2013-01-02 02:00:00,2013-01-02 03:00:00,ATMO SUD,FR02N30,PROVENCE-ALPES-COTE-D-AZUR-ZI,FR02001,Berre l'Etang,Périurbaine,C6H6,Industrielle,Oui,...,0.00,0.00000,µg-m3,NaN,NaN,NaN,A,1,43.486234,5.171939
2013-01-02 03:00:00,2013-01-02 04:00:00,ATMO SUD,FR02N30,PROVENCE-ALPES-COTE-D-AZUR-ZI,FR02001,Berre l'Etang,Périurbaine,C6H6,Industrielle,Oui,...,0.00,0.00000,µg-m3,NaN,NaN,NaN,A,1,43.486234,5.171939
2013-01-02 04:00:00,2013-01-02 05:00:00,ATMO SUD,FR02N30,PROVENCE-ALPES-COTE-D-AZUR-ZI,FR02001,Berre l'Etang,Périurbaine,C6H6,Industrielle,Oui,...,0.00,0.00000,µg-m3,NaN,NaN,NaN,A,1,43.486234,5.171939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-29 19:00:00,2022-08-29 20:00:00,ATMO SUD,FR93ZAG01,ZAG MARSEILLE-AIX,FR03043,MARSEILLE 5 AVENUES,Urbaine,SO2,Fond,Oui,...,0.70,0.67500,µg-m3,NaN,NaN,NaN,A,1,43.305287,5.394716
2022-08-29 20:00:00,2022-08-29 21:00:00,ATMO SUD,FR93ZAG01,ZAG MARSEILLE-AIX,FR03043,MARSEILLE 5 AVENUES,Urbaine,SO2,Fond,Oui,...,-0.10,-0.07500,µg-m3,NaN,NaN,NaN,A,1,43.305287,5.394716
2022-08-29 21:00:00,2022-08-29 22:00:00,ATMO SUD,FR93ZAG01,ZAG MARSEILLE-AIX,FR03043,MARSEILLE 5 AVENUES,Urbaine,SO2,Fond,Oui,...,0.50,0.52500,µg-m3,NaN,NaN,NaN,A,1,43.305287,5.394716
2022-08-29 22:00:00,2022-08-29 23:00:00,ATMO SUD,FR93ZAG01,ZAG MARSEILLE-AIX,FR03043,MARSEILLE 5 AVENUES,Urbaine,SO2,Fond,Oui,...,0.60,0.63333,µg-m3,NaN,NaN,NaN,R,1,43.305287,5.394716
2022-08-29 23:00:00,2022-08-30 00:00:00,ATMO SUD,FR93ZAG01,ZAG MARSEILLE-AIX,FR03043,MARSEILLE 5 AVENUES,Urbaine,SO2,Fond,Oui,...,0.20,0.20000,µg-m3,NaN,NaN,NaN,R,1,43.305287,5.394716

## Duplicates

We check for duplicates...

In [6]:
print(f"{len(pollutants_data_df)} rows in original, {len(pollutants_data_df.drop_duplicates())} in deduplicated")

1437864 rows in original, 1437864 in deduplicated

...and we have none.

## Clean locations

Let's look at the geographic coverage.

In [7]:
pollutants_data_df.pivot_table(
    index = ['Polluant', 'nom site']
).loc[:, ['Latitude', 'Longitude']]

                                                  Latitude  Longitude
Polluant   nom site
C6H6       Berre l'Etang                         43.486234   5.171939
           Martigues Lavera                      43.386564   5.026868
           VALLEE HUVEAUNE                       43.283341   5.511384
CO         A7 SUD LYONNAIS                       45.720024   4.818156
           Clermont-Esplanade Gare               45.775696   3.096250
           GARIBALDI                             45.768100   4.850300
           Grenoble Boulevards                   45.180690   5.720625
           Le Rondeau                            45.158363   5.703764
           Lyon Périphérique                     45.774820   4.898572
           RIVE DE GIER                          45.533424   4.623939
           ST ETIENNE ROND PT                    45.422079   4.412831
           Valence Trafic                        44.948942   4.889750
NO2        Chaptal                               43.611302   3.866260
           Montpellier Chaptal                   43.611302   3.866260
           Montpellier Prés d'Arènes             43.591500   3.886810
           Montpellier St Denis                  43.605100   3.874640
           Pompignane                            43.609600   3.898780
           Saint Denis                           43.605100   3.874640
NOX as NO2 Montpellier Chaptal                   43.611302   3.866260
           Montpellier Prés d'Arènes             43.591500   3.886810
           Pompignane                            43.609600   3.898780
O3         Montpellier Prés d'Arènes             43.591500   3.886810
           Montpellier Périurbaine Sud (Lattes)  43.570500   3.911800
           Montpellier St Gely                   43.692600   3.800210
           Périurbaine Nord                      43.692600   3.800210
           Périurbaine Sud                       43.570500   3.911800
PM10       Montpellier Prés d'Arènes             43.591500   3.886810
           Pompignane                            43.609600   3.898780
           Périurbaine Nord                      43.692600   3.800210
PM2.5      Montpellier Prés d'Arènes             43.591500   3.886810
           Pompignane                            43.609600   3.898780
SO2        MARSEILLE 5 AVENUES                   43.305287   5.394716

We can see that `Chaptal` and `Saint Denis` are repeated as `Montpellier Chaptal` and `Montpellier St Denis` with the same location. Checking the data shows that the names were changed on 1 Jan 2021, so we rename them.

In [8]:
pollutants_data_df.loc[pollutants_data_df['nom site'] == 'Chaptal', 'nom site'] = 'Montpellier Chaptal'
pollutants_data_df.loc[pollutants_data_df['nom site'] == 'Saint Denis', 'nom site'] = 'Montpellier St Denis'

We'll save the data in the current form including all pollutants as a backup.

In [9]:
pollutants_df_path = f"data/Air Quality/Historical to 2022-08-29/All pollutants.gz"

In [10]:
pollutants_data_df.to_csv(pollutants_df_path)

We also save the location data.

In [11]:
pollutants_data_df.pivot_table(
    index = ['Polluant', 'nom site'],
).to_csv('data/Air Quality/Stations with data.csv')

## Select locations, pollutants and data

We will choose only the 5 pollutants required, and we'll also select only certain measuring stations - those that are inside Montpellier, or the closest possible station where there is none in Montpellier. The records of which were chosen were created from scratch using Excel and saved as a csv.

In [12]:
stations_chosen = pd.read_csv('data/Air Quality/Air pollutants measuring stations.csv', index_col = 0)

In [13]:
with pd.option_context('display.max_colwidth', 0, 'display.colheader_justify', 'left'):
    display(stations_chosen.style.set_properties(**{'text-align': 'left'}))

We select only the data that is likely to be useful. Non urban stations are excluded as we are trying to get a forecast for Montpellier centre.

In [14]:
required_pollutants = ['NO2', 'O3', 'PM10', 'PM2.5', 'SO2']
excluded_stations = [
    'Périurbaine Nord',
    'Périurbaine Sud',
    'Montpellier Périurbaine Sud (Lattes)',
    'Montpellier St Gely'
]

pollutants = pollutants_data_df[
    (pollutants_data_df['Polluant'].isin(required_pollutants)) &
    (~pollutants_data_df['nom site'].isin(excluded_stations))
]

In [15]:
pollutants.pivot_table(
    index = ['Polluant', 'nom site']
).loc[:, ['Latitude', 'Longitude']]

                                     Latitude  Longitude
Polluant nom site
NO2      Montpellier Chaptal        43.611302   3.866260
         Montpellier Prés d'Arènes  43.591500   3.886810
         Montpellier St Denis       43.605100   3.874640
         Pompignane                 43.609600   3.898780
O3       Montpellier Prés d'Arènes  43.591500   3.886810
PM10     Montpellier Prés d'Arènes  43.591500   3.886810
         Pompignane                 43.609600   3.898780
PM2.5    Montpellier Prés d'Arènes  43.591500   3.886810
         Pompignane                 43.609600   3.898780
SO2      MARSEILLE 5 AVENUES        43.305287   5.394716

Let's look at summary info for our data as that will help us exclude other elements.

In [16]:
pollutants.info()

<class 'pandas.core.frame.DataFrame'>
Index: 841920 entries, 2013-01-02 00:00:00 to 2022-08-29 23:00:00
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Date de fin            841920 non-null  object
 1   Organisme              841920 non-null  object
 2   code zas               841920 non-null  object
 3   Zas                    841920 non-null  object
 4   code site              841920 non-null  object
 5   nom site               841920 non-null  object
 6   type d'implantation    841920 non-null  object
 7   Polluant               841920 non-null  object
 8   type d'influence       841920 non-null  object
 9   Réglementaire          841920 non-null  object
 10  type d'évaluation      841920 non-null  object
 11  type de valeur         841920 non-null  object
 12  valeur                 811823 non-null  float64
 13  valeur brute           811823 non-null  float64
 14  unité de mesure        841920 non-null  object
 15  taux de saisie         0 non-null       float64
 16  couverture temporelle  0 non-null       float64
 17  couverture de données  0 non-null       float64
 18  code qualité           841920 non-null  object
 19  validité               841920 non-null  int64
 20  Latitude               841920 non-null  float64
 21  Longitude              841920 non-null  float64
dtypes: float64(7), int64(1), object(14)
memory usage: 147.7+ MB

In [17]:
with pd.option_context('display.max_columns', None):
    display(pollutants.describe(include = 'all'))

,Date de fin,Organisme,code zas,Zas,code site,nom site,type d'implantation,Polluant,type d'influence,Réglementaire,type d'évaluation,type de valeur,valeur,valeur brute,unité de mesure,taux de saisie,couverture temporelle,couverture de données,code qualité,validité,Latitude,Longitude
count,841920,841920,841920,841920,841920,841920,841920,841920,841920,841920,841920,841920,811823.000000,811823.000000,841920,0.0,0.0,0.0,841920,841920.000000,841920.000000,841920.000000
unique,84648,2,4,4,5,5,1,5,2,1,2,2,NaN,NaN,2,NaN,NaN,NaN,3,NaN,NaN,NaN
top,2013-01-02 01:00:00,ATMO OCCITANIE,FR76ZAG02,ZAG MONTPELLIER,FR08016,Montpellier Prés d'Arènes,Urbaine,NO2,Fond,Oui,mesures fixes,moyenne horaire validée,NaN,NaN,µg-m3,NaN,NaN,NaN,A,NaN,NaN,NaN
freq,10,757560,443664,443664,337272,337272,841920,336264,504480,841920,818592,841680,NaN,NaN,717840,NaN,NaN,NaN,708654,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.539493,23.528430,NaN,NaN,NaN,NaN,NaN,0.928504,43.571573,4.038253
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.039819,23.039394,NaN,NaN,NaN,NaN,NaN,0.371323,0.089256,0.452766
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.100000,-4.125000,NaN,NaN,NaN,NaN,NaN,-1.000000,43.305287,3.866260
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.100000,7.125000,NaN,NaN,NaN,NaN,NaN,1.000000,43.591500,3.886810
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.800000,15.800000,NaN,NaN,NaN,NaN,NaN,1.000000,43.591500,3.886810
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.000000,32.025000,NaN,NaN,NaN,NaN,NaN,1.000000,43.609600,3.898780
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,205.600000,205.600000,NaN,NaN,NaN,NaN,NaN,1.000000,43.611302,5.394716

In addition to irrelevant columns, we can exclude:
- `unité de mesure` - because although there are 2 values they are the same (`µg/m3`, and `µg-m3`).
- `type d'implantation` and `Réglementaire` - because each only has one value (`urban` and `1`).
- `taux de saisie`, `couverture temporelle`, and `couverture de données` - because they have no non-null values.
- `Latitude`, and `Longitude` because we have them stored by station elsewhere.

In [18]:
pollutants = pollutants.loc[:, [
    'Polluant',
    'nom site',
    'type d\'influence',
    'type d\'évaluation',
    'type de valeur',
    'valeur',
    'valeur brute'
]]

## Final data

In [19]:
pollutants

,Polluant,nom site,type d'influence,type d'évaluation,type de valeur,valeur,valeur brute
Date de début,,,,,,,
2013-01-02 00:00:00,NO2,Montpellier Chaptal,Fond,mesures fixes,moyenne horaire validée,NaN,NaN
2013-01-02 01:00:00,NO2,Montpellier Chaptal,Fond,mesures fixes,moyenne horaire validée,NaN,NaN
2013-01-02 02:00:00,NO2,Montpellier Chaptal,Fond,mesures fixes,moyenne horaire validée,NaN,NaN
2013-01-02 03:00:00,NO2,Montpellier Chaptal,Fond,mesures fixes,moyenne horaire validée,NaN,NaN
2013-01-02 04:00:00,NO2,Montpellier Chaptal,Fond,mesures fixes,moyenne horaire validée,0.7,0.66667
...,...,...,...,...,...,...,...
2022-08-29 19:00:00,SO2,MARSEILLE 5 AVENUES,Fond,mesures fixes,moyenne horaire brute,0.7,0.67500
2022-08-29 20:00:00,SO2,MARSEILLE 5 AVENUES,Fond,mesures fixes,moyenne horaire brute,-0.1,-0.07500
2022-08-29 21:00:00,SO2,MARSEILLE 5 AVENUES,Fond,mesures fixes,moyenne horaire brute,0.5,0.52500
2022-08-29 22:00:00,SO2,MARSEILLE 5 AVENUES,Fond,mesures fixes,moyenne horaire brute,0.6,0.63333
2022-08-29 23:00:00,SO2,MARSEILLE 5 AVENUES,Fond,mesures fixes,moyenne horaire brute,0.2,0.20000

In [20]:
pollutants.to_csv('data/Air Quality/Historical to 2022-08-29/Pollutants data.gz')